#!/bin/bash
set -e

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")"

versions=( "$@" )
if [ ${#versions[@]} -eq 0 ]; then
        versions=( */ )
fi
versions=( "${versions[@]%/}" )

# get tag list from facebook/hhvm repository
response=$(curl https://api.github.com/repos/facebook/hhvm/tags)
printf '%s\n' "$( jq -r '.[] | .name' <<< $response )" >> tags

for version in "${versions[@]}"; do
    fullVersion="$( cat tags | grep HHVM-$version | head -n1 )"

        ( set -x; cp hhvm-ext-* "$version/" )

        for variant in fastcgi; do
                echo "Generating $version/$variant/Dockerfile from $variant-Dockerfile-block-*"
                awk '
                        $1 == "##</autogenerated>##" { ia = 0 }
                        !ia { print }
                        $1 == "##<autogenerated>##" { ia = 1; ab++; ac = 0 }
                        ia { ac++ }
                        ia && ac == 1 { system("cat '$variant'-Dockerfile-block-" ab) }
                ' "$version/Dockerfile" > "$version/$variant/Dockerfile"
                ( set -x; cp hhvm-ext-* "$version/$variant/" )
        done

        (
                set -x
                sed -ri '
                s/^(ENV HHVM_VERSION) .*/\1 '"$fullVersion"'/
                ' "$version/Dockerfile" "$version/"*/Dockerfile
        )
done

rm tags
